### PR TITLE
[don't merge] don't build nompi for now

### LINKED ISSUE #101: The nompi version is likely fragile... if not broken... after 8.2.0
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

We should stop packaging the nompi version because it will likely fail for certain capabilities. This is likely caused by the decision to add ParallelIO. Will submit a PR to fix, and add a test for something like `ESMF_RegridWeightGen` which seems to work only when paired with an MPI.

### Installed packages

```shell
na
```

### Environment info

```shell
na
```

### PR DESCRIPTION
**Pull request by mahf708**
fix #101 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@mahf708, a complication is that now we also have to disable Windows builds because MPI isn't available for Windows.

**Comment by xylar** [comment]
@zklaus and @ocefpaf, I'd like to get your take on how to solve #101.  Our group is finding it pretty hard to use `ESMF_RegridWeightGen` these days because we can't use conda-forge MPI on our HPC systems but the `nompi` build has also not worked since 8.3.1 and the move to ParallelIO.

I'm not sure what works and what doesn't, as that is really the only tool from ESMF that our group uses.  Maybe marking ESMF's `nompi` builds as broken over it is overkill.  But they certainly also aren't working like they did in 8.2.0 and older.

It seems a real shame to throw out the Windows build work, though.  And we can't support any MPI configurations there.

Obviously, a better solution would be for ESMF folks to come up with a fully functional no-MPI solution again.

Pinging @billsacks as well in case you have some thoughts or can pass this along to ESMF folks you're working with.

**Comment by billsacks** [comment]
@xylar thanks for pinging me on this. I discussed this more with the ESMF team today and will share the comments from that meeting:

First, our understanding of what's broken is any I/O that goes through PIO when building with nompi – which includes most of the relevant I/O of netCDF files.

There is a workaround for this that has been working on at least one system and would be our suggestion at least in the short-term and possibly even the long-term: As you may know, you can build ESMF with either its internal PIO library or an already-built external PIO library. For a packaged build, using an external PIO library probably makes sense, so that the same version of PIO can be used across multiple other packages that depend on it. What has been found to work is to build an mpiserial version of PIO (by setting PIO's CMake variable PIO_USE_MPISERIAL=ON), then building ESMF with nompi and ESMF_PIO=external (you will also need to set ESMF_PIO_INCLUDE and ESMF_PIO_LIBPATH – see http://earthsystemmodeling.org/docs/nightly/develop/ESMF_usrdoc/node10.html). I believe that, for this PIO build to work, you will need an existing build of the mpi-serial library (https://github.com/MCSclimate/mpi-serial) to satisfy PIO's dependency. The build I know of where this is working uses the Spack package manager (see https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/parallelio/package.py and https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/mpi-serial/package.py for relevant build scripts).

We are hoping to enable an ESMF build with nompi and the internal PIO library for ESMF8.6.0, but that isn't due out until the Fall, so I hope that the above strategy might work for you. Please let me know if you would like more details on this approach.

**Comment by billsacks** [comment]
> So, does this won't work readily in conda-forge, right?

I don't know enough about conda-forge to answer this. Is there a problem with relying on an external PIO package because it isn't available itself in conda-forge?

**Comment by billsacks** [comment]
> I guess we could make a "fake" PIO package

I do suppose that a serial parallel I/O package is a bit of a contradiction, but yes, that seems like the right direction if it's workable.

**Comment by xylar** [comment]
@billsacks, thank you, this is a very helpful suggestion.  I think we can make a `nompi` build of ParallelIO with your suggestion and then use that for our ESMF `nompi` builds.  That would be better than our current approach of not having ParallelIO at all.

@mahf708, thank you for pointing out that we would need to add `mpi-serial`.  I can look into that but feel free to submit a recipe to `staged_recipes` if you have time, and include me as a maintainer.

Once we have a solution, think we would go back and build working `nompi` builds for esmf 8.3.1 and later, and then mark the previous `nompi` builds for those versions as broken.  This will take some time.

**Comment by xylar** [comment]
@mahf708, at this point, I don't think we want to disable `nompi`, as that will just make things more complicated later.

**Comment by xylar** [comment]
I'm not sure how feasible it will be to have a Window build of `mpi-serial` and then `ParallelIO` using `mpi-serial`, but it should be a priority to try to support it in both.

**Comment by zklaus** [comment]
I made a start at https://github.com/conda-forge/staged-recipes/pull/22793. Feel free to disregard/replace/shutdown.

**Comment by zklaus** [comment]
`mpi-serial` is now available. How do we move forward from here?

**Comment by xylar** [comment]
@zklaus, I think the next step is to figure out all of `esmf`'s dependencies that need mpi and make PRs to those feedstocks to add `mpi_serial`.

**Comment by xylar** [comment]
Actually, I don't think that's necessary.  Presumably, we just need to do that for `openmpi`.  For other libraries, we can use the `nompi` version.

**Pull request closed without merging**
