### PR TITLE
Add windows build

### LINKED ISSUE #64: Add a windows build
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: At the moment there is no windows build in conda-forge for esmf. Given that both cygwin and mingw are supported platforms, it seems not out of the question to add this to conda-forge as well. That would be a nice addition, unlocking further downstream packages.

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Add a windows build (closes #64)

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
Needs windows build of netcdf-fortran, see conda-forge/netcdf-fortran-feedstock#3, conda-forge/netcdf-fortran-feedstock#52, conda-forge/netcdf-fortran-feedstock#60.

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
Still blocked by https://github.com/conda-forge/netcdf-fortran-feedstock/issues/3, https://github.com/conda-forge/netcdf-fortran-feedstock/pull/52, https://github.com/conda-forge/netcdf-fortran-feedstock/pull/60.

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please restart ci

**Comment by zklaus** [comment]
@conda-forge-admin, please restart ci

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Review by xylar — APPROVED** [review]
Wow, @zklaus, amazing work!  I looked through the patches and they look fine to me at a glance, though I don't feel qualified to assess them in detail.  It's good enough for me that testing works.

**Comment by xylar** [comment]
@ocefpaf and @rokuingh, do you want to review or show @zklaus merge this?

**Comment by ocefpaf** [comment]
@zklaus as @xylar already said, this is amazing! What an herculean effort! I'd love if @rokuingh could look at the patches and, if possible, upstream them. However, I'm OK merging this as-is b/c if you are the main user of this package you'll know pretty soon if it is OK or not.

PS: I'm stealing the honor of merging this now but I'll definitely buy you and @xylar a :beer: and/or :coffee: if we manage to meet in person.

**Comment by zklaus** [comment]
Cheers, guys! Very happy to see this come along.

Re upstreaming, I have the patches in a branch against upstream at https://github.com/zklaus/esmf/tree/develop-windows. The commits should be largely orthogonal, i.e. easy to cherry-pick. I'll try to do PRs myself, but won't be mad at all if someone else gets to it first ;)

Re meeting in person, that's a great idea! You wouldn't happen to be in Vienna in late April?

**Comment by ocefpaf** [comment]
> Re upstreaming, I have the patches in a branch against upstream at https://github.com/zklaus/esmf/tree/develop-windows. The commits should be largely orthogonal, i.e. easy to cherry-pick. I'll try to do PRs myself, but won't be mad at all if someone else gets to it first ;)

Awesome! I can try to send them if you are too busy.
 
> Re meeting in person, that's a great idea! You wouldn't happen to be in Vienna in late April?

I no longer have an excuse to go to Vienna (EGU) b/c I'm not doing science anymore but I hope to be back. I'll keep you posted if I land there. If you are coming to SciPy in the USA please let me know.

**Pull request merged**
