### PR TITLE
Use equivalent SPDX identifier for license (closes #66)

### LINKED ISSUE #66: Use SPDX identifier for license
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Conda-forge has moved to using [SPDX](https://spdx.org/licenses/) identifiers to unify license handling (see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions)). Since ESMF comes under [the NCSA license](https://spdx.org/licenses/NCSA.html), this is a simple change that will help with linting of future recipe changes and have no substantive impact.

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] ~~Bumped the build number (if the version is unchanged)~~ ¹
* [x] ~~Reset the build number to `0` (if the version changed)~~ ¹
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

¹build number changes deemed unnecessary due to nature of change.

Closes #66.

### CODE REVIEW

**Comment by zklaus** [comment]
Do we need to bump the build number for this non-substantive change?

**Comment by xylar** [comment]
> Do we need to bump the build number for this non-substantive change?

No, that's not necessary.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
You do need to rerender, though, or the change won't take effect.

**Comment by xylar** [comment]
Thanks for the PR and raising the issue, by the way!

**Pull request merged**
