### PR TITLE
Don't use system gfortran

### LINKED ISSUE #5: Fortran?
Looks like we are `yum` installing Fortran. Is there a good reason not to just the `gcc` package here? The problem is that as is there will be a missing `libgfortran` dependency in some cases. Is it possible for us to switch over to using the `gcc` package here?

### PR DESCRIPTION
**Pull request by ocefpaf**
Fixes #5

### CODE REVIEW

**Comment by ocefpaf** [comment]
The OS X failure is unrelated to the change.  `libnetcdf 4.3*` is picked up at build time and  `libnetcdf 4.4.0` is installed at test time :unamused: 

That is a known bug in `conda-build` that @mcg1969 is already fixing.

The annoying thing is that `libnetcdf` is installed here via `netcdf-fortran` which **is** pinned against `libnetcdf 4.3*`, so the pinning is not being respected . Also, a search for `libnetcdf` does not show that `libnetcdf 4.4.0`!

```
> conda search libnetcdf
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
libnetcdf                    4.2.1.1                       0  defaults        
                             4.2.1.1                       1  defaults        
                             4.3.2                         0  defaults        
                             4.3.2                         1  defaults        
                             4.3.3.1                       0  defaults        
                             4.3.3.1                       1  defaults        
                          .  4.3.3.1                       3  defaults
```

A workaround would be to over-specify the dependencies by pinning build/run/test to `libnetcdf 4.3*` here. However, I am against it as this is IMO a bug that must be fixed in our tools.

Ping @pelson, @msarahan, @gillins and @jakirkham for awareness in case you see this behavior in other places.

**Comment by mcg1969** [comment]
If one version of `libgfortran` works and another does not, it is _not_ "over-specifying" to put a version specification into the `run` recipe.

**Comment by mcg1969** [comment]
In fact, I argue that the "bug" I have fixed in master _isn't so much a bug_ as it is undesirably confusing behavior. The recipe it is pulling down during testing satisfies the specifications it is given.

**Comment by mcg1969** [comment]
As for `netcdf-fortran`: build 2 is pinned to `libnetcdf 4.3*`, but builds 0 and 1 are not. It's certainly going to prefer downgrading the *build* of `netcdf-fortran` over downgrading the *version* of `libnetcdf`.

**Comment by ocefpaf** [comment]
> If one version of `libgfortran` works and another does not

The issue is not related to `libgfortran` as stated above.

> it is _not_ "over-specifying" to put a version specification into the `run` recipe. In fact, it is wrong *not* to do so; see https://github.com/conda-forge/staged-recipes/issues/475

I disagree. Specifying the dependencies is needed. Specifying the dependencies of the dependencies **is** over-specifying and no package manager should require that. The burden on the maintainer to navigate down dependency trees to do so would ignore eons of package managing evolution.

> In fact, I argue that the "bug" I have fixed in conda-build master isn't so much a bug as it is undesirably confusing behavior.

That is a definition of a bug to me :smile: 

> As for `netcdf-fortran`: build 2 is pinned to `libnetcdf 4.3*`, but builds 0 and 1 are not. It's certainly going to prefer downgrading the *build* of `netcdf-fortran` over downgrading the *version* of `libnetcdf`.

Again, that is a highly undesirable behavior as we expect the specified dependencies to be optimized due to constants updates on the recipes. Anyways, I guess we are stuck with this behavior. Let's hope that removing the previous builds on `netcdf-fortran` will ensure that the latest version with the proper pinning is chosen.

Thank you for taking time to assess this issue.

**Comment by mcg1969** [comment]
> Again, that is a highly undesirable behavior as we expect the specified dependencies to be optimized due to constants updates on the recipes.

This is an expectation that needs to be discarded. You have no control over the environments into which people are installing these packages, and as such you cannot count on the optimizations you _happen_ to see during the build and test processes.

**Comment by ocefpaf** [comment]
> As for netcdf-fortran: build 2 is pinned to libnetcdf 4.3*, but builds 0 and 1 are not. It's certainly going to prefer downgrading the build of netcdf-fortran over downgrading the version of libnetcdf.

Also note that, from a packager point of view, build number are sometimes in equal to higher importance as version numbers. Build numbers are, 99% of the time, fixing broken/incomplete/buggy builds! I see more cases where downgrading the version is less damaging than downgrading the build number.

Of course we can delete old builds, but that is a behavior frowned upon from a reproducibility and provenance point of view.

**Comment by mcg1969** [comment]
> Of course we can delete old builds, but that is a behavior frowned upon from a reproducibility and provenance point of view.

You can also do metadata hot fixes. In my view it is a necessary evil.

Even if you _were_ to delete the packages from the repo, you haven't prevented someone who has _already installed_ the package from using it incorrectly.

**Comment by mcg1969** [comment]
I'm actually open to modifying `conda`'s optimization behavior with regards to build numbers. Perhaps we can discuss this in a fresh `conda/conda` issue. But there is no amount of rejiggering that will eliminate the need to be appropriately tight on version specs.

**Comment by ocefpaf** [comment]
From https://github.com/conda-forge/esmf-feedstock/pull/6#issuecomment-215975577 and https://github.com/conda-forge/esmf-feedstock/pull/6#issuecomment-215975666 all I can see is you making my point that: respecting the specified dependencies and raising an issue if they cannot be satisfied would be better than the current behavior.

Anyways, it is clear that you disagree and I am OK working around this issue. I am not OK over-specifying dependencies though as that is a big step back in packing.

> I'm actually open to modifying `conda`'s optimization behavior with regards to build numbers. Perhaps we can discuss this in a fresh `conda/conda` issue.

I am glad to hear that!

> But there is no amount of rejiggering that will eliminate the need to be appropriately tight on version specs.

There is no sliver bullet and I don't expect one :smiley:

**Comment by mcg1969** [comment]
> respecting the specified dependencies and raising an issue if they cannot be satisfied would be better than the current behavior.

I seem to be missing something. Even before my recent conda-build fix, it *was* respecting the specified dependencies. It just wasn't *optimizing* them the way you like.

I need to make this point as clear as I can: *you cannot depend on optimization behavior.* That's an extremely dangerous thing to do, because the optimization process is *global*, taking into account every single package found in the environment, and the specific command the user is issuing. Constraints introduced outside of your control as a package manager will inevitably change the optimization result.

The *only* thing you have control over is the dependency constraints. So for instance, if you specify `libgfortran` as a dependency, _knowing_ that an older version of `libgfortran` doesn't work, your package is not going to work for some people. And it will fail silently, which is even worse.

**Comment by mcg1969** [comment]
Just so I am clear: suppose a package has the following `run` entry.
```
run:
  - libgfortran
```
It seems like you are interpreting interpreting this as follows: *install the latest version of `libgfortran` available*. 

That's not the case. All this is telling `conda` is *some version of `libgfortran` must be installed*. That's it. Every version of libgfortran available is a legitimate candidate for installation.

Yes, `conda` has an optimization pass that will, _among other things_, attempt to get the latest possible version of `libgfortran`. But it can't _guarantee_ that it will do so, because that guarantee may conflict with all of those aforementioned "other things" it is trying to optimize. For instance, another package might pin it's `libgfortran` version with an incompatible one. And if that happens, your package has raised no objection.

**Comment by ocefpaf** [comment]
Again, the dependency issue here has nothing to do with `gfortran`.

**Comment by mcg1969** [comment]
Yes, I apologize for the confusion, I think I got `libgfortran` and `libnetcdf` mixed up above.

**Pull request merged**
