### PR TITLE
rebuild for HDF5 1.14.2

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The bot has this in "Awaiting PR" status, unsure why or what that means, so am doing manually like #103

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
Oye, why didn't any CI jobs run, erm :cry:

**Comment by ocefpaf** [comment]
We are seeing some issues with Azure... Stand-by for more info.

**Comment by akrherz** [comment]
OK, the bot got this in #108

**Pull request closed without merging**
