### PR TITLE
Closes #13

### LINKED ISSUE #13: ESMF app installation does not respect install prefix on Darwin
Use `install_name_tool` in build script until fix is available in a tagged ESMF version.

### PR DESCRIPTION
**Pull request by ocefpaf**
@bekozi does this looks OK to you?

### CODE REVIEW

**Comment by bekozi** [comment]
Not quite. There is a missing variable:

`ESMF_ORIGINAL_LIB_PATH=/Users/travis/miniconda3/conda-bld/work/esmf/lib/libO/Darwin.gfortran.64.mpiuni.default/libesmf.dylib`

This should stay consistent in the conda environment. A `find` could make it more portable. Do you have a trick for this? Thanks for doing the PR. :smile:

**Comment by ocefpaf** [comment]
> Thanks for doing the PR. :smile: 

I figured you are busy since you opened the issue instead of a PR :wink:

> This should stay consistent in the conda environment.

Checking that now...

**Comment by ocefpaf** [comment]
@bekozi looking into this a little further I realized we will need to use `@rpath` to get it right. So conda will always find it for any env. Not sure if something like this would work b/c I don't have a Mac:

`install_name_tool -change @loader_path/libesmf.dylib @rpath/../../libesmf.dylib ${ESMF_APP_PATH}`

Do you have a Mac? Can you try that? (Closing this for lack of hardware to iterate :unamused: )

**Comment by ocefpaf** [comment]
See [here](https://github.com/conda/conda-recipes/blob/0dabe789218ef58df023154dfc6482791b336451/python/numpy-openblas/build.sh) for an example.

**Comment by bekozi** [comment]
The `@rpath` is added by `patchelf` so changing the library path name to the install location allows `conda build` to work its magic. See: https://travis-ci.org/NESII/esmf-feedstock/builds/142832181#L2756

I don't have a Mac either, but using Travis-CI for these sorts of things work fine...as long as you're patient.

**Comment by ocefpaf** [comment]
> I don't have a Mac either, but using Travis-CI for these sorts of things work fine...as long as you're patient.

I will give it another go later today. Before calling quits :smile:

**Comment by bekozi** [comment]
My testing indicates the approach we have here will work, so let me know if you find out something different.

**Comment by ocefpaf** [comment]
@bekozi does this look OK to you?

**Comment by bekozi** [comment]
Almost. :smile: The path is still wrong in [the `otool` output](https://travis-ci.org/conda-forge/esmf-feedstock/builds/143416517#L6052) from the `test` section of `meta.yaml`. I think this is because `find .` is used which will yield a relative path and not the absolute path needed by `install_name_tool` which is looking for exact matches. You could try ```$(find `pwd` ...)``` instead.

**Comment by ocefpaf** [comment]
Trying that now...

PS: I commented `mack check` out just to iterate faster. So if this works we cannot merge until I revert that.

**Comment by bekozi** [comment]
> PS: I commented mack check out just to iterate faster. So if this works we cannot merge until I revert that.

I did that too!

**Comment by ocefpaf** [comment]
How about now? (I really need to buy a Mac o do this sort of things...)

**Comment by bekozi** [comment]
Links look good! :tada: 

> I really need to buy a Mac o do this sort of things...

No kidding. I need one too. The cloud solutions are all too expensive.

**Comment by ocefpaf** [comment]
Removing the commented out tests and running one last time. If you are OK with the result feel free to merge. (I am clocking out for the day.)

PS: Next week is SciPy in Austin. I will try to get help for the `mpich` recipe there from the other conda-forge core devs.

**Comment by bekozi** [comment]
> Removing the commented out tests and running one last time. If you are OK with the result feel free to merge. (I am clocking out for the day.)

Will do. Thanks a lot for seeing this through.

> PS: Next week is SciPy in Austin. I will try to get help for the mpich recipe there from the other conda-forge core devs.

Safe travels and enjoy the conference! I'll be out next week as well (not at the conference though).

**Comment by ocefpaf** [comment]
> Safe travels and enjoy the conference! I'll be out next week as well (not at the conference though).

Enjoy your break!

**Pull request merged**
