### PR TITLE
Add activate/deactivate scripts

### LINKED ISSUE #105: ESMFMKFILE does not seem to be properly set for Windows environments
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It appears that `ESMFMKFILE` is not being properly set for packages build upon ESMF in Windows. This env var should probably be set within the conda-forge package.

```
(base) %SRC_DIR%>conda activate "%PREFIX%" 
import: 'xscen'
Traceback (most recent call last):
  File "C:\bld\xscen_1692289661119\_test_env\Lib\site-packages\esmpy\interface\loadESMF.py", line 26, in <module>
    esmfmk = os.environ["ESMFMKFILE"]
             ~~~~~~~~~~^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'ESMFMKFILE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bld\xscen_1692289661119\_test_env\Lib\site-packages\xesmf\backend.py", line 22, in <module>
    import esmpy as ESMF
  File "C:\bld\xscen_1692289661119\_test_env\Lib\site-packages\esmpy\__init__.py", line 112, in <module>
    from esmpy.api.esmpymanager import *
  File "C:\bld\xscen_1692289661119\_test_env\Lib\site-packages\esmpy\api\esmpymanager.py", line 9, in <module>
    from esmpy.interface.cbindings import *
  File "C:\bld\xscen_1692289661119\_test_env\Lib\site-packages\esmpy\interface\cbindings.py", line 13, in <module>
    from esmpy.interface.loadESMF import _ESMF
  File "C:\bld\xscen_1692289661119\_test_env\Lib\site-packages\esmpy\interface\loadESMF.py", line 28, in <module>
    raise ImportError('The ESMFMKFILE environment variable is not available.')
ImportError: The ESMFMKFILE environment variable is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\bld\xscen_1692289661119\test_tmp\run_test.py", line 2, in <module>
    import xscen
  File "C:\bld\xscen_1692289661119\_test_env\Lib\site-packages\xscen\__init__.py", line 5, in <module>
    from . import (
  File "C:\bld\xscen_1692289661119\_test_env\Lib\site-packages\xscen\aggregate.py", line 16, in <module>
    import xesmf as xe
  File "C:\bld\xscen_1692289661119\_test_env\Lib\site-packages\xesmf\__init__.py", line 4, in <module>
    from .frontend import Regridder, SpatialAverager
  File "C:\bld\xscen_1692289661119\_test_env\Lib\site-packages\xesmf\frontend.py", line 12, in <module>
    from .backend import Grid, LocStream, Mesh, add_corner, esmf_regrid_build, esmf_regrid_finalize
  File "C:\bld\xscen_1692289661119\_test_env\Lib\site-packages\xesmf\backend.py", line 24, in <module>
    import ESMF
ModuleNotFoundError: No module named 'ESMF'
```

### Installed packages

```shell
Prefix: C:\Miniforge

  Updating specs:

   - xscen=0.6.0[build=pyhd8ed1ab_0]
   - cartopy
   - cf_xarray[version='>=0.7.6']
   - cftime
   - clisops[version='>=0.9.5']
   - dask-core
   - flox
   - fsspec
   - geopandas
   - h5netcdf
   - intake
   - intake-esm[version='>=2022.9.18']
   - matplotlib-base
   - netcdf4
   - numpy
   - pandas !=1.5.3
   - pyarrow
   - pygeos
   - python[version='>=3.8']
   - pyyaml
   - rechunker
   - shapely
   - xarray[version='<2023.3.0']
   - xclim[version='>=0.37']
   - xesmf[version='>=0.7']
   - zarr
   - pip
   - python
```

### Environment info

```shell
N/A (Running on Azure/conda-forge)
```

### PR DESCRIPTION
**Pull request by xylar**
These were previously in ESMPy but should be here in part because ESMPy is now `noarch: python`.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #105

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerende

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@ocefpaf, please have a look when you have time.  @zklaus, if you are back from your time off, please have a look as well.

@rokuingh, I'm not sure what your availability is but you're welcome to take a look, of course.

**Review by ocefpaf — APPROVED** [review]
LGTM, maybe we should add a https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#downstream-tests for esmpy here?

**Comment by xylar** [comment]
@ocefpaf, wow!  I wasn't aware of downstream tests.  Let's see how it goes...

**Comment by xylar** [comment]
@ocefpaf, that doesn't seem to have worked:
```
Mamba failed to solve:
 - esmpy 8.4.2.* pyhc1e730c_1
 - esmf 8.4.2.*
 - numpy
 - python >=3.7
 - esmf 8.4.2.* mpi_mpich_*
 - pytest-json-report
 - pip
 - python

with channels:
 - file:///home/conda/feedstock_root/build_artifacts

The reported errors are:
- Encountered problems while solving:
-   - package esmf-8.4.2-mpi_mpich_h8fb3fe9_101 is excluded by strict repo priority
- 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 141, in mamba_get_install_actions
    solution = solver.solve_for_action(_specs, prefix)
  File "/opt/conda/lib/python3.10/site-packages/boa/core/solver.py", line 244, in solve_for_action
    t = self.solve(specs)
  File "/opt/conda/lib/python3.10/site-packages/boa/core/solver.py", line 234, in solve
    raise RuntimeError("Solver could not find solution." + error_string)
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - esmpy 8.4.2.* pyhc1e730c_1
 - esmf 8.4.2.*
 - numpy
 - python >=3.7
 - esmf 8.4.2.* mpi_mpich_*
 - pytest-json-report
 - pip
 - python

with channels:
 - file:///home/conda/feedstock_root/build_artifacts

The reported errors are:
- Encountered problems while solving:
-   - package esmf-8.4.2-mpi_mpich_h8fb3fe9_101 is excluded by strict repo priority
```
It seems like it's trying to test with mpich, regardless of the actual MPI build.

**Comment by xylar** [comment]
Okay, I'll remove my last commit.

**Pull request merged**
